sonar.projectKey=occulo_php-project-57
sonar.organization=occulo

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=php-project-57
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=app,routes
sonar.tests=tests

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/**,database/migrations/**

sonar.php.coverage.reportPaths=coverage.xml

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8